name: lectly_client_user_mobile
description: hearsome is an easy Speech-to-Text tool.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  get:
  flutter_native_splash: ^2.1.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  internet_connection_checker: ^0.0.1+3
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.0
  permission_handler: ^9.2.0
  flutter_sound: ^9.2.13
  http: ^0.13.4
  dio: ^4.0.6
  intl: ^0.17.0
  just_audio: ^0.9.11
  audio_session: ^0.1.6
  path_provider: ^2.0.10
  file: ^6.1.2

  flutter_resources: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/v-logo.png
    - assets/images/h-logo.png
    - assets/images/on_boarding.png
    - assets/images/google_logo.png
    - assets/images/user.png
    - assets/images/mic.png
    - assets/images/warning.png
    - assets/images/globe.png
    - assets/images/egyptian_flag.png
    - assets/images/american_flag.png
    - assets/images/arrow.png
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Medium.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
